Wegmeister:
  Hyphenator:
    patternPath: '%FLOW_PATH_PACKAGES%Plugins/Wegmeister.Hyphenator/Configuration/patterns/'
    dictionary: '%FLOW_PATH_ROOT%Configuration/Production/dictionary.txt'
    hyphen: '­' # utf-8 char for the html &shy; entity
    altHyphen: '&shy;'
    excludeTags:
      code: TRUE
      pre: TRUE
      script: TRUE
      style: TRUE
    leftmin: 2
    rightmin: 2
    shortestPattern: 5
    longestPattern: 10
    wordBoundaries: "<>\t\n\r\0\x0B !\"§$%&/()=?….,;:-–_„”«»‘’'/\\‹›()[]{}*+´`^|©?®™?¹²³"
    locales:
      'de': 'de_DE'
      'en': 'en_GB'


TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Wegmeister.Hyphenator': TRUE
